/* tslint:disable */
/* eslint-disable */
/**
 * Moda API Document
 * Moda API 명세서 입니다.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiSuccessResponse } from './api-base.types';

export interface AccountCreateRequest {
  /** 계좌 비밀번호 */
  accountPassword: string;
  /** 계좌 별칭 */
  accountAlias?: string;
}

export interface AccountCreateResponse {
  /** 계좌번호 */
  accountNo: string;
  /** 계좌순번 */
  accountSequence: string;
  /** 표시순번 */
  visibleSequence: string;
}

export interface AccountInfo {
  /** 계좌번호 */
  accountNo: string;
  /** 계좌순번 */
  accountSequence: string;
  /** 등급그룹코드 */
  accountGrade: string;
  /** 계좌별칭 */
  accountAlias: string;
  /** 표시여부 */
  visible: string;
  /** 표시순번 */
  visibleSequence: string;
  /** 출금가능금액 */
  availableWithdrawAmount?: string;
}

export interface AccountInfoResponse {
  /** 계좌 리스트 */
  accountList: Array<AccountInfo>;
}

export interface AccountInfoUpdateRequest {
  /** 계좌 정보 목록 */
  accountInfos: Array<ItemDto>;
}

export interface AccountUpdatePwdRequest {
  /** 계좌번호 */
  accountNo: string;
  /** 변경 전 비밀번호 */
  beforeAccountPassword: string;
  /** 변경 후 비밀번호 */
  afterAccountPassword: string;
}

export interface AccountAvailableWithdrawalAmountResponse {
  /** 계좌별 예수금/출금가능금액 리스트 */
  amountList: Array<ItemDto>;
}

export interface ItemDto {
  /** 계좌번호 */
  accountNo: string;
  /** 계좌별칭 */
  accountAlias: string;
  /** 표시여부 */
  visible: string;
}

export interface ResponseDataAccountCreateResponse
  extends ApiSuccessResponse<AccountCreateResponse> {}

export interface ResponseDataAccountInfoResponse extends ApiSuccessResponse<AccountInfoResponse> {}

export interface ResponseDataAccountAvailableWithdrawalAmountResponse
  extends ApiSuccessResponse<AccountAvailableWithdrawalAmountResponse> {}

export interface AccountDepositsWithdrawalsInfoRequest {
  /** 전체조회 flag */
  isAllAccounts: boolean;
  /** 계좌번호 */
  accountNo: string;
  /** 거래구분 */
  depositsWithdrawalsCode: AccountDepositsWithdrawalsInfoRequestDepositsWithdrawalsCodeType;
  /** 신청 시작일자 */
  requestStartDate: string;
  /** 신청 종료일자 */
  requestEndDate: string;
  /** nextKey(초기 요청시 empty) */
  nextKey: string;
}

/**
 * @export
 */
export type AccountDepositsWithdrawalsInfoRequestDepositsWithdrawalsCodeType =
  | 'ALL'
  | 'DEPOSIT'
  | 'WITHDRAWAL'
  | 'TRANSFER';

export interface AccountDepositsWithdrawalsInfoResponse {
  /** 계좌 리스트 */
  accountList: Array<ItemDto>;
}

export interface ResponseDataAccountDepositsWithdrawalsInfoResponse
  extends ApiSuccessResponse<AccountDepositsWithdrawalsInfoResponse> {}

export interface WithdrawalRequest {
  /** 계좌번호 */
  accountNo: string;
  /** 계좌비밀번호 */
  accountPassword: string;
  /** 출납구분코드 (WITHDRAWAL=출금, TRANSFER=이체) */
  withdrawalDivisionCode: WithdrawalRequestWithdrawalDivisionCodeType;
  /** 신청금액($) */
  amount: number;
  /** 입금은행코드 */
  receivingBankCode: string;
  /** 입금계좌번호 */
  receivingAccountNo: string;
  /** 이체계좌번호 */
  transferAccountNo: string;
}

/**
 * @export
 */
export type WithdrawalRequestWithdrawalDivisionCodeType =
  | 'ALL'
  | 'DEPOSIT'
  | 'WITHDRAWAL'
  | 'TRANSFER';

export interface ResponseDataUnit extends ApiSuccessResponse<object> {}

export interface AccountStockData {
  /** 종목코드 */
  stockCd: string;
  /** 증거금율 */
  marginRate: number;
}

export interface AccountStockRequest {
  /** 계좌번호 */
  accountNo: string;
  /** nextKey(초기 요청시 1) */
  nextKey: string;
}

export interface AccountStockResponse {
  /** 다음페이지 존재여부 */
  hasNext: boolean;
  /** 다음페이지 조회키 */
  nextKey: string;
  /** 계좌종목 목록 */
  stocks: Array<AccountStockData>;
}

export interface ResponseDataAccountStockResponse
  extends ApiSuccessResponse<AccountStockResponse> {}

/**
 * 입금신청 요청 (FormData)
 * OpenAPI Generator가 생성하지 않은 타입 (폼 파라미터)
 */
export interface DepositRequest {
  /** 입금 영수증 파일 */
  transferReceipt: File;
}
