/* tslint:disable */
/* eslint-disable */
/**
 * Moda API Document
 * Moda API 명세서 입니다.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiSuccessResponse } from './api-base.types';

export interface ResponseDataObject {
  /** status */
  status: string;
  /** code */
  code: number;
  /** data */
  data?: object;
}

export interface ResponseDataString {
  /** status */
  status: string;
  /** code */
  code: number;
  /** data */
  data?: string;
}

export interface Email {
  /** */
  value: string;
}

export interface StockCode {
  /** */
  value: string;
}

export interface CustomProblemDetail {
  /** 에러 타입 URI */
  type?: string;
  /** 에러 제목 */
  title?: string;
  /** HTTP 상태 코드 */
  status?: number;
  /** 에러 상세 메시지 */
  detail?: string;
  /** 에러 발생 경로 */
  instance?: string;
  /** 비즈니스 에러 코드 */
  code?: string;
  /** 에러 발생 시각 */
  timestamp?: string;
  /** 검증 실패 상세 정보 */
  validation?: object | null;
}

export interface OrderResponseDto {
  /** */
  trCode: string;
  /** */
  trGb: string;
  /** */
  handle: string;
  /** */
  copCd: string;
  /** */
  empNo: string;
  /** */
  grdGrcd: string;
  /** */
  userIp: string;
  /** */
  dataGrp: string;
  /** */
  user: string;
  /** */
  rcnt: number;
  /** */
  items?: Array<OrderResponseItemDto>;
}

export interface OrderResponseItemDto {
  /** */
  isuCd: string;
  /** */
  ppr: number;
  /** */
  mgnRt: number;
  /** */
  stdCcyCd: string;
  /** */
  trdCcyCd: string;
  /** */
  lotMtp: number;
  /** */
  prMtp: number;
  /** */
  potUnt: number;
  /** */
  pipUnt: number;
}

export interface BalanceResponseDto {
  /** */
  trCode: string;
  /** */
  trGb: string;
  /** */
  handle: string;
  /** */
  copCd: string;
  /** */
  empNo: string;
  /** */
  grdGrcd: string;
  /** */
  userIp: string;
  /** */
  dataGrp: string;
  /** */
  user: string;
  /** */
  rcnt?: number;
  /** */
  items?: Array<BalanceResponseItemDto>;
}

export interface BalanceResponseItemDto {
  /** */
  isuCd: string;
  /** */
  trdCcyCd: string;
  /** */
  posDvcd: number;
  /** */
  abkQty: number;
  /** */
  abkPr: number;
  /** */
  ppr: number;
  /** */
  evlPl: number;
  /** */
  pftRt: number;
  /** */
  isuGrcd: string;
}

export interface ResponseDataBalanceResponseDto extends ApiSuccessResponse<BalanceResponseDto> {}

export interface ResponseDataOrderResponseDto extends ApiSuccessResponse<OrderResponseDto> {}

export interface CandleChartResponse {
  /** 시간 */
  time: number;
  /** 매도호가-시가 */
  open: number;
  /** 매도호가-고가 */
  high: number;
  /** 매도호가-저가 */
  low: number;
  /** 매도호가-종가 */
  close: number;
}

export interface ResponseListCandleChartResponse {
  /** */
  contents: Array<CandleChartResponse>;
}

export interface ResponseDataResponseListCandleChartResponse
  extends ApiSuccessResponse<ResponseListCandleChartResponse> {}

export interface TickChartResponse {
  /** 시간 */
  time: number;
  /** 매도호가 */
  price: number;
}

export interface ResponseListTickChartResponse {
  /** */
  contents: Array<TickChartResponse>;
}

export interface ResponseDataResponseListTickChartResponse
  extends ApiSuccessResponse<ResponseListTickChartResponse> {}
