/* tslint:disable */
/* eslint-disable */
/**
 * Moda API Document
 * Moda API 명세서 입니다.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiSuccessResponse } from './api-base.types';

export interface PositionStockRequest {
  /** 계좌번호 */
  accountNo: string;
  /** 종목 코드 */
  stockCd: string;
  /** nextKey(초기 요청시 1) */
  nextKey: string;
}

export interface PositionStockResponse {
  /** 다음페이지 존재여부 */
  hasNext: boolean;
  /** 다음페이지 조회키 */
  nextKey: string;
  /** 주문잔고 목록 */
  symbols: Array<PositionStockData>;
}

export interface PossessionStockRequest {
  /** 계좌번호 */
  accountNo: string;
  /** nextKey(초기 요청시 1) */
  nextKey: string;
}

export interface PossessionStockResponse {
  /** 다음페이지 존재여부 */
  hasNext: boolean;
  /** 다음페이지 조회키 */
  nextKey: string;
  /** 보유종목 코드 목록 */
  stocks: Array<string>;
}

export interface OrderStockRequest {
  /** 종목 그룹코드 */
  stockGroupCd: OrderStockRequestStockGroupCdType;
  /** 종목 코드 */
  stockCd: string;
}

/**
 * @export
 */
export type OrderStockRequestStockGroupCdType =
  | 'ALL'
  | 'FOREIGN'
  | 'INDEX'
  | 'COMMODITY'
  | 'CRYPTO';

export interface OrderStockResponse {
  /** 다음페이지 존재여부 */
  hasNext: boolean;
  /** 다음페이지 조회키 */
  nextKey: string;
  /** 종목 메타데이터 */
  details: Array<StockMetaData>;
  /** 종목별 현재가 정보 */
  currentPrices: { [key: string]: string };
}

export interface PositionStockData {
  /** 종목코드 */
  stockCd: string;
  /** 거래통화코드 */
  tradeCurrencyCd: string;
  /** 포지션구분코드 */
  positionCd: PositionStockDataPositionCdType;
  /** 매입일자 */
  purchaseDate: string;
  /** 장부수량 */
  accountBookQuantity: number;
  /** 청산가능수량 */
  liquidationPossibleQuantity: number;
  /** 장부가격 */
  accountBookPrice: number;
  /** 현재가 */
  currentPrice: number;
  /** 평가손익 */
  assessmentProfitLoss: number;
  /** (H) 종목그룹코드 */
  stockGroupCd: PositionStockDataStockGroupCdType;
  /** (H) 잔고번호 */
  positionNo: string;
}

/**
 * @export
 */
export type PositionStockDataPositionCdType = 'TOTAL' | 'LONG' | 'SHORT';
/**
 * @export
 */
export type PositionStockDataStockGroupCdType =
  | 'ALL'
  | 'FOREIGN'
  | 'INDEX'
  | 'COMMODITY'
  | 'CRYPTO';

export interface StockMetaData {
  /** 종목코드 */
  stockCd: string;
  /** (H) 기준통화코드 */
  standardCurrencyCd: string;
  /** (H) 거래통화코드 */
  tradeCurrencyCd: string;
  /** (H) Lot승수 */
  lotMultiple: number;
  /** (H) Price승수 */
  priceMultiplier: number;
  /** (H) Point단위 */
  pointUnit: number;
  /** (H) Pip단위 */
  pipUnit: number;
  /** (H) 종목그룹코드 */
  stockGroupCd: StockMetaDataStockGroupCdType;
  /** (H) 심볼그룹코드 */
  symbolGroupCd: string;
  /** (H) 증거금율사용여부 */
  isMarginUsage: boolean;
  /** (H) 증거금율(%) */
  marginRate: number;
  /** (H) 스프레드사용여부 */
  isSpreadUsage: boolean;
  /** (H) 매수스프레드 */
  buySpread: number;
  /** (H) 매도스프레드 */
  sellSpread: number;
  /** (H) 전일종가 */
  closePrice: number;
  /** Monday 거래시작시각 */
  monTradeStartTime: string;
  /** Monday 거래종료시각 */
  monTradeEndTime: string;
  /** Tuesday 거래시작시각 */
  tueTradeStartTime: string;
  /** Tuesday 거래종료시각 */
  tueTradeEndTime: string;
  /** Wednesday 거래시작시각 */
  wedTradeStartTime: string;
  /** Wednesday 거래종료시각 */
  wedTradeEndTime: string;
  /** Thursday 거래시작시각 */
  thuTradeStartTime: string;
  /** Thursday 거래종료시각 */
  thuTradeEndTime: string;
  /** Friday 거래시작시각 */
  friTradeStartTime: string;
  /** Friday 거래종료시각 */
  friTradeEndTime: string;
  /** Saturday 거래시작시각 */
  satTradeStartTime: string;
  /** Saturday 거래종료시각 */
  satTradeEndTime: string;
  /** Sunday 거래시작시각 */
  sunTradeStartTime: string;
  /** Sunday 거래종료시각 */
  sunTradeEndTime: string;
}

/**
 * @export
 */
export type StockMetaDataStockGroupCdType = 'ALL' | 'FOREIGN' | 'INDEX' | 'COMMODITY' | 'CRYPTO';

export interface ResponseDataPositionStockResponse
  extends ApiSuccessResponse<PositionStockResponse> {}

export interface ResponseDataPossessionStockResponse
  extends ApiSuccessResponse<PossessionStockResponse> {}

export interface ResponseDataOrderStockResponse extends ApiSuccessResponse<OrderStockResponse> {}

export interface ResponseListOrderBookResponse {
  /** */
  contents: Array<OrderBookResponse>;
}

export interface OrderBookResponse {
  /** 매수호가 */
  bid: string;
  /** 매도호가 */
  ask: string;
  /** 매수호가수량 */
  bidSize: string;
  /** 매도호가수량 */
  askSize: string;
}

export interface ResponseDataResponseListOrderBookResponse
  extends ApiSuccessResponse<ResponseListOrderBookResponse> {}

export interface OrderNewRequest {
  /** 계좌번호 */
  accountNo: string;
  /** 계좌비밀번호 */
  accountPassword: string;
  /** */
  stockCd: string;
  /** 주문유형코드 */
  orderTypeCd: OrderNewRequestOrderTypeCdType;
  /** 매매구분코드 */
  sideCd: OrderNewRequestSideCdType;
  /** 주문수량 */
  orderQuantity: number;
  /** 배리어가격 */
  barrierPrice: number;
  /** 주문가격 */
  orderPrice: number;
  /** 이익실현여부 */
  profitRealizationYn: string;
  /** 이익실현배리어가격 */
  profitRealizationBarrierPrice: number;
  /** 손실제한여부 */
  lossCutYn: string;
  /** 손실제한배리어가격 */
  lossCutBarrierPrice: number;
  /** 손실추적여부 */
  lossTrackingYn: string;
}

/**
 * @export
 */
export type OrderNewRequestOrderTypeCdType = 'MARKET' | 'LIMIT' | 'STOP' | 'LIMIT_STOP' | 'TPSL';
/**
 * @export
 */
export type OrderNewRequestSideCdType = 'BUY' | 'SELL_TO_CLOSE' | 'SELL' | 'BUY_TO_COVER';

export interface OrderNewResponse {
  /** 주문일자 */
  orderDate: string;
  /** 주문번호 */
  orderNo: string;
  /** 접수일시 */
  receptionDate: string;
}

export interface ResponseDataOrderNewResponse extends ApiSuccessResponse<OrderNewResponse> {}

export interface OrderCancelRequest {
  /** 계좌번호 */
  accountNo: string;
  /** 계좌비밀번호 */
  accountPassword: string;
  /** 주문유형코드 */
  orderTypeCd: OrderCancelRequestOrderTypeCdType;
  /** 매매구분코드 */
  sideCd: OrderCancelRequestSideCdType;
  /** 주문일자 */
  orderDate: string;
  /** 주문번호 */
  orderNo: string;
}

/**
 * @export
 */
export type OrderCancelRequestOrderTypeCdType = 'MARKET' | 'LIMIT' | 'STOP' | 'LIMIT_STOP' | 'TPSL';
/**
 * @export
 */
export type OrderCancelRequestSideCdType = 'BUY' | 'SELL_TO_CLOSE' | 'SELL' | 'BUY_TO_COVER';

export interface OrderCancelResponse {
  /** 성공 여부 */
  success: boolean;
}

export interface ResponseDataOrderCancelResponse extends ApiSuccessResponse<OrderCancelResponse> {}

export interface OrderCloseOutRequest {
  /** 계좌번호 */
  accountNo: string;
  /** 계좌비밀번호 */
  accountPassword: string;
  /** */
  stockCd: string;
  /** 주문유형코드 */
  orderTypeCd: OrderCloseOutRequestOrderTypeCdType;
  /** 매매구분코드 */
  sideCd: OrderCloseOutRequestSideCdType;
  /** 주문수량 */
  orderQuantity: number;
  /** 배리어가격 */
  barrierPrice: number;
  /** 주문가격 */
  orderPrice: number;
  /** 매입일자 */
  purchaseDate: string;
  /** 잔고번호 */
  balanceNo: string;
}

/**
 * @export
 */
export type OrderCloseOutRequestOrderTypeCdType =
  | 'MARKET'
  | 'LIMIT'
  | 'STOP'
  | 'LIMIT_STOP'
  | 'TPSL';
/**
 * @export
 */
export type OrderCloseOutRequestSideCdType = 'BUY' | 'SELL_TO_CLOSE' | 'SELL' | 'BUY_TO_COVER';

export interface OrderCloseOutResponse {
  /** 주문일자 */
  orderDate: string;
  /** 주문번호 */
  orderNo: string;
  /** 접수일시 */
  receptionDate: string;
}

export interface ResponseDataOrderCloseOutResponse
  extends ApiSuccessResponse<OrderCloseOutResponse> {}

export interface OrderModifyRequest {
  /** 계좌번호 */
  accountNo: string;
  /** 계좌비밀번호 */
  accountPassword: string;
  /** */
  stockCd: string;
  /** 주문유형코드 */
  orderTypeCd: OrderModifyRequestOrderTypeCdType;
  /** 매매구분코드 */
  sideCd: OrderModifyRequestSideCdType;
  /** 주문일자 */
  orderDate: string;
  /** 주문번호 */
  orderNo: string;
  /** 주문수량 */
  orderQuantity: number;
  /** 배리어가격 */
  barrierPrice: number;
  /** 주문가격 */
  orderPrice: number;
  /** 이익실현여부 (청산주문 시 null) */
  profitRealizationYn?: string;
  /** 이익실현배리어가격 (청산주문 시 null) */
  profitRealizationBarrierPrice?: number;
  /** 손실제한여부 (청산주문 시 null) */
  lossCutYn?: string;
  /** 손실제한배리어가격 (청산주문 시 null) */
  lossCutBarrierPrice?: number;
  /** 손실추적여부 (청산주문 시 null) */
  lossTrackingYn?: string;
}

/**
 * @export
 */
export type OrderModifyRequestOrderTypeCdType = 'MARKET' | 'LIMIT' | 'STOP' | 'LIMIT_STOP' | 'TPSL';
/**
 * @export
 */
export type OrderModifyRequestSideCdType = 'BUY' | 'SELL_TO_CLOSE' | 'SELL' | 'BUY_TO_COVER';

export interface OrderModifyResponse {
  /** 성공 여부 */
  success: boolean;
}

export interface ResponseDataOrderModifyResponse extends ApiSuccessResponse<OrderModifyResponse> {}

export interface OrderTpslRequest {
  /** 계좌번호 */
  accountNo: string;
  /** 계좌비밀번호 */
  accountPassword: string;
  /** */
  stockCd: string;
  /** 매매구분코드 */
  sideCd: OrderTpslRequestSideCdType;
  /** TPSL액션타입 */
  tpslActionType: OrderTpslRequestTpslActionType;
  /** 주문일자 */
  orderDate: string;
  /** 주문번호 */
  orderNo: string;
  /** 주문수량 */
  orderQuantity: number;
  /** 이익실현여부 */
  profitRealizationYn: string;
  /** 이익실현배리어가격 */
  profitRealizationBarrierPrice?: number;
  /** 손실제한여부 */
  lossReturnYn: string;
  /** 손실제한배리어가격 */
  lossReturnBarrierPrice?: number;
  /** 손실추격여부 */
  lossTrackingYn: string;
  /** 매입일자 */
  purchaseDate?: string;
  /** 잔고번호 */
  balanceNo?: string;
}

/**
 * @export
 */
export type OrderTpslRequestSideCdType = 'BUY' | 'SELL_TO_CLOSE' | 'SELL' | 'BUY_TO_COVER';
/**
 * @export
 */
export type OrderTpslRequestTpslActionType = 'NEW' | 'MODIFY';

export interface OrderTpslResponse {
  /** 주문일자 */
  orderDate: string;
  /** 주문번호 */
  orderNo: string;
  /** 접수일시 */
  receptionDate: string;
}

export interface ResponseDataOrderTpslResponse extends ApiSuccessResponse<OrderTpslResponse> {}
