/* tslint:disable */
/* eslint-disable */
/**
 * Moda API Document
 * Moda API 명세서 입니다.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiSuccessResponse } from './api-base.types';

export interface OrderExecutionHistoryRequest {
  /** 계좌번호 */
  accountNo: string;
  /** 주문 시작일자 */
  orderStartDate: string;
  /** 주문 종료일자 */
  orderEndDate: string;
  /** 주문구분코드 */
  orderCd: OrderExecutionHistoryRequestOrderCdType;
  /** 포지션구분코드 */
  positionCd: OrderExecutionHistoryRequestPositionCdType;
  /** nextKey(초기 요청시 1) */
  nextKey: string;
}

/**
 * @export
 */
export type OrderExecutionHistoryRequestOrderCdType = 'TOTAL' | 'PURCHASE' | 'CLOSE_OUT';
/**
 * @export
 */
export type OrderExecutionHistoryRequestPositionCdType = 'TOTAL' | 'LONG' | 'SHORT';

export interface OrderExecutionHistoryResponse {
  /** 다음페이지 존재여부 */
  hasNext: boolean;
  /** 다음페이지 조회키 */
  nextKey: string;
  /** 요약 정보 */
  summary: Array<SummaryOrderExecution>;
  /** 상세 정보 */
  details: Array<DetailsOrderExecution>;
}

export interface PaymentHistoryRequest {
  /** 계좌번호 */
  accountNo: string;
  /** 청산 시작일자 */
  orderStartDate: string;
  /** 청산 종료일자 */
  orderEndDate: string;
  /** nextKey(초기 요청시 1) */
  nextKey: string;
}

export interface PaymentHistoryResponse {
  /** 다음페이지 존재여부 */
  hasNext: boolean;
  /** 다음페이지 조회키 */
  nextKey: string;
  /** 상세 정보 */
  details: Array<PaymentDetail>;
}

export interface DetailsOrderExecution {
  /** 주문일자 */
  orderDate: string;
  /** 주문번호 */
  orderNo: string;
  /** 체결일자 */
  executionDate: string;
  /** 체결번호 */
  executionNo: string;
  /** 종목코드 */
  stockCd: string;
  /** 포지션구분코드 */
  positionCd: DetailsOrderExecutionPositionCdType;
  /** 주문유형코드 */
  orderTypeCd: DetailsOrderExecutionOrderTypeCdType;
  /** 주문구분코드 */
  orderCd: DetailsOrderExecutionOrderCdType;
  /** 주문수량 */
  orderQuantity: number;
  /** 배리어가격 */
  barrierPrice: number;
  /** 주문가격 */
  orderPrice: number;
  /** 이익실현배리어가격 */
  profitRealizationBarrierPrice: number;
  /** 손실제한배리어가격 */
  lossCutBarrierPrice: number;
  /** 체결수량 */
  executionQuantity: number;
  /** 체결가격 */
  executionPrice: number;
  /** 주문잔량 */
  orderBalance: number;
  /** 주문상태코드 */
  orderStatusCd: DetailsOrderExecutionOrderStatusCdType;
  /** 접수일시 */
  receptionDate: string;
  /** 거부사유명 */
  rejectReason: string;
}

/**
 * @export
 */
export type DetailsOrderExecutionPositionCdType = 'TOTAL' | 'LONG' | 'SHORT';
/**
 * @export
 */
export type DetailsOrderExecutionOrderTypeCdType =
  | 'MARKET'
  | 'LIMIT'
  | 'STOP'
  | 'LIMIT_STOP'
  | 'TPSL';
/**
 * @export
 */
export type DetailsOrderExecutionOrderCdType = 'TOTAL' | 'PURCHASE' | 'CLOSE_OUT';
/**
 * @export
 */
export type DetailsOrderExecutionOrderStatusCdType =
  | 'RECEIVED'
  | 'SENT'
  | 'CONFIRMED'
  | 'REJECTED'
  | 'BARRIER'
  | 'LIMIT_PRICE'
  | 'FAILED'
  | 'CLOSED';

export interface SummaryOrderExecution {
  /** 거래통화코드 */
  tradeCurrencyCd: string;
  /** 매수체결수량 */
  longExecutionQuantity: number;
  /** 매수체결금액 */
  longExecutionPrice: number;
  /** 전매체결수량 */
  reShortExecutionQuantity: number;
  /** 전매체결금액 */
  reShortExecutionPrice: number;
  /** 매도체결수량 */
  shortExecutionQuantity: number;
  /** 매도체결금액 */
  shortExecutionPrice: number;
  /** 환매체결수량 */
  reLongExecutionQuantity: number;
  /** 환매체결금액 */
  reLongExecutionPrice: number;
}

export interface PaymentDetail {
  /** 결제일자 */
  paymentDate: string;
  /** 종목코드 */
  stockCd: string;
  /** 적요명 */
  description: string;
  /** 거래통화코드 */
  tradeCurrencyCd: string;
  /** 포지션구분코드 */
  positionCd: PaymentDetailPositionCdType;
  /** 거래구분코드 */
  tradeCd: PaymentDetailTradeCdType;
  /** 체결수량 */
  executionQuantity: number;
  /** 체결가격 */
  executionPrice: number;
  /** 체결금액 */
  executionAmount: number;
  /** 결제금액($) */
  paymentAmount: number;
  /** 이전장부수량 */
  beforeBookQuantity: number;
  /** 이후장부수량 */
  afterBookQuantity: number;
  /** 이전예수금($) */
  beforeDeposit: number;
  /** 이후예수금($) */
  afterDeposit: number;
}

/**
 * @export
 */
export type PaymentDetailPositionCdType = 'TOTAL' | 'LONG' | 'SHORT';
/**
 * @export
 */
export type PaymentDetailTradeCdType =
  | 'BUY_PURCHASE'
  | 'CLOSE_OUT'
  | 'DEPOSIT'
  | 'WITHDRAWAL'
  | 'DESCRIPTION_DEPOSIT'
  | 'DESCRIPTION_WITHDRAWAL';

export interface ResponseDataOrderExecutionHistoryResponse
  extends ApiSuccessResponse<OrderExecutionHistoryResponse> {}

export interface ResponseDataPaymentHistoryResponse
  extends ApiSuccessResponse<PaymentHistoryResponse> {}

export interface TradeUnExecutionHistoryRequest {
  /** 계좌번호 */
  accountNo: string;
  /** nextKey(초기 요청시 1) */
  nextKey: string;
}

export interface TradeUnExecutionHistoryResponse {
  /** 다음페이지 존재여부 */
  hasNext: boolean;
  /** 다음페이지 조회키 */
  nextKey: string;
  /** 상세 정보 */
  details: Array<DetailsPendingOrder>;
}

export interface ResponseDataTradeUnExecutionHistoryResponse
  extends ApiSuccessResponse<TradeUnExecutionHistoryResponse> {}

export interface CloseOutHistoryRequest {
  /** 계좌번호 */
  accountNo: string;
  /** 주문 시작일자 */
  orderStartDate: string;
  /** 주문 종료일자 */
  orderEndDate: string;
  /** nextKey(초기 요청시 1) */
  nextKey: string;
}

export interface CloseOutHistoryResponse {
  /** 다음페이지 존재여부 */
  hasNext: boolean;
  /** 다음페이지 조회키 */
  nextKey: string;
  /** */
  summary: CloseOutSummary;
  /** 상세 정보 */
  details: Array<CloseOutDetail>;
}

export interface ResponseDataCloseOutHistoryResponse
  extends ApiSuccessResponse<CloseOutHistoryResponse> {}

export interface CloseOutOrderHistoryRequest {
  /** 계좌번호 */
  accountNo: string;
  /** 청산 시작일자 */
  orderStartDate: string;
  /** 청산 종료일자 */
  orderEndDate: string;
  /** nextKey(초기 요청시 1) */
  nextKey: string;
}

export interface CloseOutOrderHistoryResponse {
  /** 다음페이지 존재여부 */
  hasNext: boolean;
  /** 다음페이지 조회키 */
  nextKey: string;
  /** 상세 정보 */
  details: Array<DetailsCloseOutOrder>;
}

export interface ResponseDataCloseOutOrderHistoryResponse
  extends ApiSuccessResponse<CloseOutOrderHistoryResponse> {}

export interface TradeHistoryRequest {
  /** 계좌번호 */
  accountNo: string;
  /** 청산 시작일자 */
  orderStartDate: string;
  /** 청산 종료일자 */
  orderEndDate: string;
  /** nextKey(초기 요청시 1) */
  nextKey: string;
}

export interface TradeHistoryResponse {
  /** 다음페이지 존재여부 */
  hasNext: boolean;
  /** 다음페이지 조회키 */
  nextKey: string;
  /** 상세 정보 */
  details: Array<DetailsOrderExecution>;
}

export interface ResponseDataTradeHistoryResponse
  extends ApiSuccessResponse<TradeHistoryResponse> {}

export interface DetailsPendingOrder {
  /** 주문일자 */
  orderDate: string;
  /** 주문번호 */
  orderNo: string;
  /** 종목코드 */
  stockCd: string;
  /** 포지션구분코드 */
  positionCd: DetailsPendingOrderPositionCdType;
  /** 주문유형코드 */
  orderTypeCd: DetailsPendingOrderOrderTypeCdType;
  /** 주문구분코드 */
  orderCd: DetailsPendingOrderOrderCdType;
  /** 주문수량 */
  orderQuantity: number;
  /** 배리어가격 */
  barrierPrice: number;
  /** 주문가격 */
  orderPrice: number;
  /** 이익실현배리어가격 */
  profitRealizationBarrierPrice: number;
  /** 손실제한배리어가격 */
  lossCutBarrierPrice: number;
  /** 주문잔량 */
  orderBalance: number;
  /** 주문상태코드 */
  orderStatusCd: DetailsPendingOrderOrderStatusCdType;
  /** 접수일시 */
  receptionDate: string;
  /** (H) 이익실현여부 */
  isProfitExecution: string;
  /** (H) 손실제한여부 */
  isLossLimits: string;
  /** (H) 손실추적여부 */
  isLossTracing: string;
}

/**
 * @export
 */
export type DetailsPendingOrderPositionCdType = 'TOTAL' | 'LONG' | 'SHORT';
/**
 * @export
 */
export type DetailsPendingOrderOrderTypeCdType =
  | 'MARKET'
  | 'LIMIT'
  | 'STOP'
  | 'LIMIT_STOP'
  | 'TPSL';
/**
 * @export
 */
export type DetailsPendingOrderOrderCdType = 'TOTAL' | 'PURCHASE' | 'CLOSE_OUT';
/**
 * @export
 */
export type DetailsPendingOrderOrderStatusCdType =
  | 'RECEIVED'
  | 'SENT'
  | 'CONFIRMED'
  | 'REJECTED'
  | 'BARRIER'
  | 'LIMIT_PRICE'
  | 'FAILED'
  | 'CLOSED';

export interface CloseOutSummary {
  /** LONG 취득금액($) */
  longAcquisitionPrice: number;
  /** LONG 청산금액($) */
  longCloseOutPrice: number;
  /** LONG 청산손익($) */
  longCloseOutProfitLoss: number;
  /** LONG 청산수익율 */
  longCloseOutProfitPercent: number;
  /** LONG 스왑수수료($) */
  longSwapCharge: number;
  /** LONG 체결수수료($) */
  longExecutionCharge: number;
  /** LONG 청산순손익($) */
  longCloseOutNetProfitLoss: number;
  /** LONG 청산순수익율 */
  longCloseOutNetProfitPercent: number;
  /** SHORT 취득금액($) */
  shortAcquisitionPrice: number;
  /** SHORT 청산금액($) */
  shortCloseOutPrice: number;
  /** SHORT 청산손익($) */
  shortCloseOutProfitLoss: number;
  /** SHORT 청산수익율 */
  shortCloseOutProfitPercent: number;
  /** SHORT 스왑수수료($) */
  shortSwapCharge: number;
  /** SHORT 체결수수료($) */
  shortExecutionCharge: number;
  /** SHORT 청산순손익($) */
  shortCloseOutNetProfitLoss: number;
  /** SHORT 청산순수익율 */
  shortCloseOutNetProfitPercent: number;
  /** nextKey(초기 요청시 1) */
  nextKey: string;
}

export interface CloseOutDetail {
  /** 청산일자 */
  closeOutDate: string;
  /** 종목코드 */
  stockCd: string;
  /** 포지션 구분 */
  positionCd: CloseOutDetailPositionCdType;
  /** 매입가격 */
  purchasePrice: number;
  /** 청산가격 */
  closeOutPrice: number;
  /** 청산수량 */
  closeOutQuantity: number;
  /** 청산손익 */
  closeOutProfitLoss: number;
  /** 스왑수수료 */
  swapCharge: number;
  /** 체결수수료 */
  tradeCharge: number;
  /** 청산순손익 */
  closeOutNetProfitLoss: number;
  /** 매입일시 */
  purchaseDateTime: string;
  /** 청산일시 */
  closeOutDateTime: string;
}

/**
 * @export
 */
export type CloseOutDetailPositionCdType = 'TOTAL' | 'LONG' | 'SHORT';

export interface DetailsCloseOutOrder {
  /** 주문일자 */
  orderDate: string;
  /** 주문번호 */
  orderNo: string;
  /** 체결일자 */
  executionDate: string;
  /** 종목코드 */
  stockCd: string;
  /** 거래통화코드 */
  tradeCurrencyCd: string;
  /** 포지션구분코드 */
  positionCd: DetailsCloseOutOrderPositionCdType;
  /** 청산수량 */
  closeOutQuantity: number;
  /** 매입가격 */
  purchasePrice: number;
  /** 청산가격 */
  closeOutPrice: number;
  /** 청산손익($) */
  closeOutProfitLoss: number;
  /** 체결수수료($) */
  executionFee: number;
  /** 스왑수수료($) */
  swapFee: number;
}

/**
 * @export
 */
export type DetailsCloseOutOrderPositionCdType = 'TOTAL' | 'LONG' | 'SHORT';
