/* tslint:disable */
/* eslint-disable */
/**
 * Moda API Document
 * Moda API 명세서 입니다.
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiSuccessResponse } from './api-base.types';
import { StockCode } from './common.types';

export interface WatchListAddRequest {
  /** */
  stockCode: string;
}

export interface WatchListResponse {
  /** 종목 코드 */
  stockCode: string;
}

export interface ResponseDataListWatchListResponse {
  /** status */
  status: string;
  /** code */
  code: number;
  /** data */
  data?: Array<WatchListResponse>;
}
